
import React, { useState, useMemo, useEffect } from 'react';
import { WoundAnalysisResult, MeasurementLine, TunnelingRecord, UnderminingRecord } from '../types';
import { MeasurementOverlay } from './MeasurementOverlay';

interface ResultViewProps {
  result: WoundAnalysisResult;
  image: string;
  onReset: () => void;
  onBack: () => void;
  onSave: (patientName: string, updatedResult: WoundAnalysisResult) => void;
  isEditing?: boolean;
  initialPatientName?: string;
}

const PERI_WOUND_OPTIONS = [
  'Intact', 'Macerated', 'Erythematous', 'Indurated', 'Dry/Scaly', 'Pigmented', 'Excoriated', 'Other'
];

const DEPTH_OPTIONS = Array.from({ length: 101 }, (_, i) => (i * 0.1).toFixed(1));
const CLOCK_OPTIONS = [12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11];

const ResultView: React.FC<ResultViewProps> = ({ result, image, onReset, onBack, onSave, isEditing, initialPatientName }) => {
  const safeLengthLine = result.lengthLine || { start: { x: 0.2, y: 0.5 }, end: { x: 0.8, y: 0.5 } };
  const safeWidthLine = result.widthLine || { start: { x: 0.5, y: 0.2 }, end: { x: 0.5, y: 0.8 } };

  const [editedLength, setEditedLength] = useState<MeasurementLine>(safeLengthLine);
  const [editedWidth, setEditedWidth] = useState<MeasurementLine>(safeWidthLine);
  const [manualDepth, setManualDepth] = useState<number>(result.depthCm || 0);
  const [activeMetric, setActiveMetric] = useState<'length' | 'width' | 'depth' | 'none'>('none');
  const [isSwapped, setIsSwapped] = useState(false);
  const [isSaveDialogOpen, setIsSaveDialogOpen] = useState(false);
  const [patientName, setPatientName] = useState(initialPatientName || '');
  
  const [tunneling, setTunneling] = useState<TunnelingRecord[]>(result.tunneling || []);
  const [undermining, setUndermining] = useState<UnderminingRecord[]>(result.undermining || []);
  const [tissueTypes, setTissueTypes] = useState(result.tissueTypes || { epithelization: 0, granulation: 0, slough: 0, eschar: 0 });
  
  const [selectedPeriWoundTags, setSelectedPeriWoundTags] = useState<string[]>(
    result.periWoundAppearance ? result.periWoundAppearance.split(', ').filter(t => PERI_WOUND_OPTIONS.includes(t)) : []
  );
  const [customPeriWound, setCustomPeriWound] = useState(
    result.periWoundAppearance?.split(', ').find(t => !PERI_WOUND_OPTIONS.includes(t) && t !== '') || ''
  );

  useEffect(() => {
    if (initialPatientName) setPatientName(initialPatientName);
  }, [initialPatientName]);

  const calculateDistance = (currentLine: MeasurementLine, originalLine: MeasurementLine, originalCm: number) => {
    const dist = (p1: any, p2: any) => Math.sqrt(Math.pow(p2.x - p1.x, 2) + Math.pow(p2.y - p1.y, 2));
    const currentLen = dist(currentLine.start, currentLine.end);
    const originalLen = dist(originalLine.start, originalLine.end);
    if (originalLen === 0) return originalCm || 0;
    return Number(((currentLen / originalLen) * (originalCm || 1)).toFixed(2));
  };

  const currentLengthCm = useMemo(() => calculateDistance(editedLength, safeLengthLine, result.lengthCm), [editedLength, safeLengthLine, result]);
  const currentWidthCm = useMemo(() => calculateDistance(editedWidth, safeWidthLine, result.widthCm), [editedWidth, safeWidthLine, result]);

  const displayLength = Number((isSwapped ? currentWidthCm : currentLengthCm).toFixed(2));
  const displayWidth = Number((isSwapped ? currentLengthCm : currentWidthCm).toFixed(2));
  const displayDepth = Number(manualDepth.toFixed(2));
  const displayArea = Number((displayLength * displayWidth * 0.785).toFixed(2));

  const lengthAdjusted = displayLength !== result.lengthCm;
  const widthAdjusted = displayWidth !== result.widthCm;
  const depthAdjusted = displayDepth !== result.depthCm;
  const isAnyAdjusted = lengthAdjusted || widthAdjusted || depthAdjusted;

  const generateReportText = () => {
    const combinedPeriWound = [...selectedPeriWoundTags.filter(t => t !== 'Other'), ...(selectedPeriWoundTags.includes('Other') && customPeriWound ? [customPeriWound] : [])].join(', ');
    return `ARROW WOUND CLINICAL REPORT\nPatient: ${patientName || 'Anonymous'}\nDate: ${new Date().toLocaleString()}\n\nMEASUREMENTS:\n- Length: ${displayLength} cm\n- Width: ${displayWidth} cm\n- Depth: ${displayDepth} cm\n- Area: ${displayArea} cm²\n\nTISSUE:\n- Epithelialization: ${tissueTypes.epithelization}%\n- Granulation: ${tissueTypes.granulation}%\n- Slough: ${tissueTypes.slough}%\n- Eschar: ${tissueTypes.eschar}%\n\nPERI-WOUND:\n${combinedPeriWound || 'Intact'}\n\nGenerated by ArrowWound Pro.`;
  };

  const handleDownloadReport = () => {
    const reportText = generateReportText();
    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Wound_Report_${patientName || 'Clinic'}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleShareReport = async () => {
    const reportText = generateReportText();
    if (navigator.share) {
      try {
        await navigator.share({
          title: `Wound Report: ${patientName || 'Clinic'}`,
          text: reportText,
        });
      } catch (err) {
        console.error("Error sharing:", err);
      }
    } else {
      // Fallback for browsers that don't support Web Share API
      navigator.clipboard.writeText(reportText);
      alert("Report copied to clipboard. (Device sharing not supported in this browser)");
    }
  };

  const togglePeriWoundTag = (tag: string) => {
    setSelectedPeriWoundTags(prev => 
      prev.includes(tag) ? prev.filter(t => t !== tag) : [...prev, tag]
    );
  };

  const updateTunnel = (idx: number, updates: Partial<TunnelingRecord>) => {
    const next = [...tunneling];
    next[idx] = { ...next[idx], ...updates };
    setTunneling(next);
  };

  const updateUndermining = (idx: number, updates: Partial<UnderminingRecord>) => {
    const next = [...undermining];
    next[idx] = { ...next[idx], ...updates };
    setUndermining(next);
  };

  const handleSaveSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!patientName.trim()) return;
    const combinedPeriWound = [...selectedPeriWoundTags.filter(t => t !== 'Other'), ...(selectedPeriWoundTags.includes('Other') && customPeriWound ? [customPeriWound] : [])].join(', ');
    onSave(patientName, { 
      ...result, 
      lengthCm: displayLength, 
      widthCm: displayWidth, 
      depthCm: displayDepth, 
      areaCm2: displayArea, 
      tunneling, 
      undermining, 
      tissueTypes, 
      periWoundAppearance: combinedPeriWound, 
      lengthLine: editedLength, 
      widthLine: editedWidth, 
      isManualAdjustment: isAnyAdjusted, 
      originalValues: isAnyAdjusted ? { lengthCm: result.lengthCm, widthCm: result.widthCm, depthCm: result.depthCm } : undefined 
    });
    setIsSaveDialogOpen(false);
  };

  return (
    <div className="p-6 space-y-6 max-w-2xl mx-auto pb-32 animate-in fade-in duration-500">
      <div className="flex justify-between items-center">
        <div className="flex items-center gap-3">
          <button onClick={onBack} className="text-slate-500 p-2 -ml-2 hover:bg-blue-50 hover:text-blue-600 rounded-full transition-all active:bg-blue-100 flex items-center gap-2">
            <i className="fa-solid fa-arrow-left"></i>
            <span className="text-sm font-bold">Back</span>
          </button>
          <h2 className="text-2xl font-bold text-gray-800">Clinical Results</h2>
        </div>
        <div className="flex gap-2">
          {isAnyAdjusted && (
            <div className="bg-red-50 text-red-600 px-3 py-1.5 rounded-lg text-[10px] font-black uppercase tracking-widest border border-red-100 shadow-sm animate-pulse">
              <i className="fa-solid fa-location-arrow mr-1"></i> Calibrated
            </div>
          )}
          <button onClick={handleShareReport} className="px-3 py-1.5 text-xs bg-blue-600 text-white rounded-lg font-bold hover:bg-blue-700 transition-all shadow-md active:scale-95" title="Share via SMS/Email">
            <i className="fa-solid fa-share-nodes"></i>
          </button>
          <button onClick={handleDownloadReport} className="px-3 py-1.5 text-xs bg-slate-900 text-white rounded-lg font-bold hover:bg-black transition-all shadow-md active:scale-95" title="Download TXT Report">
            <i className="fa-solid fa-file-arrow-down"></i>
          </button>
        </div>
      </div>

      <div className="rounded-2xl overflow-hidden shadow-2xl border border-gray-100 relative bg-black aspect-video flex items-center justify-center">
        <img src={`data:image/jpeg;base64,${image}`} alt="Wound" className="w-full h-full object-contain" />
        <MeasurementOverlay lengthLine={editedLength} widthLine={editedWidth} isSwapped={isSwapped} activeLine={activeMetric === 'length' ? 'length' : activeMetric === 'width' ? 'width' : 'none'} onUpdate={(l, w) => { setEditedLength(l); setEditedWidth(w); }} />
        {activeMetric !== 'none' && activeMetric !== 'depth' && (
          <div className="absolute top-4 right-4 bg-blue-600/90 backdrop-blur-md px-4 py-2 rounded-xl border border-white/20 text-white text-[10px] font-black uppercase tracking-[0.1em] shadow-xl animate-in zoom-in duration-200">
            Fine-Tuning {activeMetric}
          </div>
        )}
      </div>

      <div className="space-y-4">
        <div className="flex items-center justify-between px-1">
          <h3 className="font-bold text-slate-800 flex items-center gap-2">
            <i className="fa-solid fa-location-arrow text-red-600"></i> Wound Mapping
          </h3>
          <button onClick={() => setIsSwapped(!isSwapped)} className={`px-4 py-2 text-[10px] font-black uppercase tracking-widest rounded-full border-2 transition-all duration-300 active:bg-blue-800 active:text-white ${isSwapped ? 'bg-blue-600 border-blue-600 text-white shadow-lg' : 'bg-white border-slate-200 text-slate-500 hover:border-blue-600 hover:text-blue-600'}`}>
            <i className="fa-solid fa-rotate mr-2"></i> Swap Axes
          </button>
        </div>

        <div className="grid grid-cols-2 gap-4">
          <MetricCard label="Length" value={`${displayLength} cm`} icon="fa-arrows-left-right" isActive={activeMetric === 'length'} isVerified={lengthAdjusted} onClick={() => setActiveMetric(activeMetric === 'length' ? 'none' : 'length')} />
          <MetricCard label="Width" value={`${displayWidth} cm`} icon="fa-arrows-up-down" isActive={activeMetric === 'width'} isVerified={widthAdjusted} onClick={() => setActiveMetric(activeMetric === 'width' ? 'none' : 'width')} />
          <MetricCard label="Depth" value={`${displayDepth} cm`} icon="fa-layer-group" isActive={activeMetric === 'depth'} isVerified={depthAdjusted} highlight onClick={() => setActiveMetric(activeMetric === 'depth' ? 'none' : 'depth')} />
          <MetricCard label="Area" value={`${displayArea} cm²`} icon="fa-chart-area" />
        </div>
      </div>

      <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200 space-y-4">
        <h3 className="font-bold text-slate-800 flex items-center gap-2">
          <i className="fa-solid fa-droplet text-blue-500"></i> Tissue Identification (%)
        </h3>
        <div className="grid grid-cols-1 gap-4">
          <TissueRow label="Epithelialization" color="bg-pink-400" value={tissueTypes.epithelization} onChange={(v) => setTissueTypes(p => ({...p, epithelization: parseInt(v)||0}))} description="New pink skin" />
          <TissueRow label="Granulation" color="bg-red-500" value={tissueTypes.granulation} onChange={(v) => setTissueTypes(p => ({...p, granulation: parseInt(v)||0}))} description="Healthy red tissue" />
          <TissueRow label="Slough" color="bg-yellow-200" value={tissueTypes.slough} onChange={(v) => setTissueTypes(p => ({...p, slough: parseInt(v)||0}))} description="Yellow/tan debris" />
          <TissueRow label="Eschar" color="bg-neutral-800" value={tissueTypes.eschar} onChange={(v) => setTissueTypes(p => ({...p, eschar: parseInt(v)||0}))} description="Necrotic tissue" />
        </div>
      </div>

      <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200 space-y-4">
        <h3 className="font-bold text-slate-800 flex items-center gap-2">
          <i className="fa-solid fa-person-circle-check text-blue-600"></i>
          Peri-wound Assessment
        </h3>
        <div className="flex flex-wrap gap-2">
          {PERI_WOUND_OPTIONS.map(tag => (
            <button 
              key={tag}
              onClick={() => togglePeriWoundTag(tag)}
              className={`text-xs font-bold px-4 py-2 rounded-full border transition-all ${
                selectedPeriWoundTags.includes(tag)
                  ? 'bg-blue-600 text-white border-blue-600 shadow-md' 
                  : 'bg-white text-slate-500 border-slate-200 hover:bg-blue-50'
              }`}
            >
              {tag}
            </button>
          ))}
        </div>
        {selectedPeriWoundTags.includes('Other') && (
          <textarea 
            value={customPeriWound}
            onChange={(e) => setCustomPeriWound(e.target.value)}
            placeholder="Additional observations..."
            className="w-full h-24 p-4 bg-slate-50 border border-slate-200 rounded-xl text-sm outline-none resize-none transition-all focus:border-blue-400"
          />
        )}
      </div>

      <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200 space-y-6">
        <h3 className="font-bold text-slate-800 flex items-center gap-2">
          <i className="fa-solid fa-compass text-blue-500"></i>
          Clock Mapping (Depth)
        </h3>
        <div className="space-y-4">
          <div className="flex justify-between items-center border-b pb-2">
            <span className="text-xs font-black uppercase text-slate-400">Tunneling</span>
            <button onClick={() => setTunneling([...tunneling, { startClock: 12, endClock: 12, depthCm: 0.5 }])} className="text-[10px] bg-blue-50 text-blue-600 px-3 py-1 rounded-full font-bold">+ Add</button>
          </div>
          {tunneling.map((t, i) => (
            <div key={i} className="grid grid-cols-4 gap-2 items-center bg-slate-50 p-2 rounded-lg">
              <select value={t.startClock} onChange={e => updateTunnel(i, { startClock: Number(e.target.value) })} className="text-[10px] p-1 rounded bg-white border border-slate-200 font-bold">{CLOCK_OPTIONS.map(n => <option key={n} value={n}>{n}:00</option>)}</select>
              <select value={t.endClock} onChange={e => updateTunnel(i, { endClock: Number(e.target.value) })} className="text-[10px] p-1 rounded bg-white border border-slate-200 font-bold">{CLOCK_OPTIONS.map(n => <option key={n} value={n}>{n}:00</option>)}</select>
              <select value={t.depthCm} onChange={e => updateTunnel(i, { depthCm: Number(e.target.value) })} className="text-[10px] p-1 rounded bg-white border border-slate-200 font-bold">{DEPTH_OPTIONS.map(d => <option key={d} value={Number(d)}>{d} cm</option>)}</select>
              <button onClick={() => setTunneling(tunneling.filter((_, idx) => idx !== i))} className="text-red-400 text-xs hover:text-red-600"><i className="fa-solid fa-trash-can"></i></button>
            </div>
          ))}
          <div className="flex justify-between items-center border-b pb-2 mt-4">
            <span className="text-xs font-black uppercase text-slate-400">Undermining</span>
            <button onClick={() => setUndermining([...undermining, { startClock: 12, endClock: 3, depthCm: 0.5 }])} className="text-[10px] bg-blue-50 text-blue-600 px-3 py-1 rounded-full font-bold">+ Add</button>
          </div>
          {undermining.map((u, i) => (
            <div key={i} className="grid grid-cols-4 gap-2 items-center bg-slate-50 p-2 rounded-lg">
              <select value={u.startClock} onChange={e => updateUndermining(i, { startClock: Number(e.target.value) })} className="text-[10px] p-1 rounded bg-white border border-slate-200 font-bold">{CLOCK_OPTIONS.map(n => <option key={n} value={n}>{n}:00</option>)}</select>
              <select value={u.endClock} onChange={e => updateUndermining(i, { endClock: Number(e.target.value) })} className="text-[10px] p-1 rounded bg-white border border-slate-200 font-bold">{CLOCK_OPTIONS.map(n => <option key={n} value={n}>{n}:00</option>)}</select>
              <select value={u.depthCm} onChange={e => updateUndermining(i, { depthCm: Number(e.target.value) })} className="text-[10px] p-1 rounded bg-white border border-slate-200 font-bold">{DEPTH_OPTIONS.map(d => <option key={d} value={Number(d)}>{d} cm</option>)}</select>
              <button onClick={() => setUndermining(undermining.filter((_, idx) => idx !== i))} className="text-red-400 text-xs hover:text-red-600"><i className="fa-solid fa-trash-can"></i></button>
            </div>
          ))}
        </div>
      </div>

      <div className="flex flex-col gap-4">
        <button onClick={() => setIsSaveDialogOpen(true)} className="w-full bg-blue-600 text-white font-black py-5 rounded-2xl shadow-xl hover:bg-blue-700 transition-all active:bg-blue-800 flex items-center justify-center gap-3">
          <i className="fa-solid fa-floppy-disk"></i> {isEditing ? 'Update Clinical Record' : 'Save To Local Files'}
        </button>
        
        <button onClick={handleShareReport} className="w-full bg-slate-900 text-white font-black py-5 rounded-2xl shadow-xl hover:bg-black transition-all active:bg-black flex items-center justify-center gap-3">
          <i className="fa-solid fa-share-nodes"></i> Share Report (SMS/Email/Bluetooth)
        </button>
      </div>

      <div className="text-center pt-8 border-t border-slate-100">
        <button 
          onClick={onReset} 
          className="w-full bg-red-50 border-2 border-red-200 text-red-600 font-black py-5 rounded-2xl shadow-sm hover:bg-red-100 hover:border-red-300 transition-all flex items-center justify-center gap-3 active:scale-[0.98] active:bg-red-200"
        >
          <i className="fa-solid fa-trash-can"></i>
          Discard and Return Home
        </button>
        <p className="mt-2 text-[10px] font-bold text-slate-400 uppercase tracking-[0.2em]">Session ID: {Date.now().toString().slice(-8)}</p>
      </div>

      {isSaveDialogOpen && (
        <div className="fixed inset-0 bg-black/60 z-[100] flex items-center justify-center p-6 backdrop-blur-sm">
          <div className="bg-white rounded-3xl w-full max-w-sm p-8 space-y-6 shadow-2xl animate-in zoom-in-95">
            <h3 className="text-2xl font-bold text-slate-800">Archive Record</h3>
            <form onSubmit={handleSaveSubmit} className="space-y-6">
              <input 
                autoFocus 
                type="text" 
                placeholder="Patient Name / ID" 
                className="w-full border-2 border-slate-100 rounded-2xl p-4 focus:border-blue-600 outline-none font-bold text-lg" 
                value={patientName} 
                onChange={(e) => setPatientName(e.target.value)} 
                disabled={isEditing} 
              />
              <div className="flex gap-4">
                <button 
                  type="button" 
                  onClick={() => setIsSaveDialogOpen(false)} 
                  className="flex-1 py-4 font-black text-slate-500 bg-slate-50 rounded-2xl border border-slate-100 hover:bg-slate-100 transition-all uppercase text-xs tracking-widest"
                >
                  Cancel
                </button>
                <button 
                  type="submit" 
                  disabled={!patientName.trim()} 
                  className="flex-1 bg-blue-600 text-white py-4 rounded-2xl font-black shadow-lg shadow-blue-200 hover:bg-blue-700 active:bg-blue-800 transition-all disabled:opacity-30 uppercase text-xs tracking-widest"
                >
                  {isEditing ? 'Update' : 'Save'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

const TissueRow: React.FC<{ label: string; color: string; value: number; onChange: (v: string) => void; description: string }> = ({ label, color, value, onChange, description }) => (
  <div className="flex flex-col gap-1 p-3 bg-slate-50/50 rounded-xl hover:bg-slate-50 transition-colors">
    <div className="flex items-center gap-4">
      <div className={`w-3 h-3 rounded-full ${color}`}></div>
      <div className="flex-1 text-sm font-bold text-slate-700">{label}</div>
      <div className="flex items-center gap-3">
        <input 
          type="range" 
          min="0" 
          max="100" 
          value={value} 
          onChange={(e) => onChange(e.target.value)} 
          className="w-32 accent-blue-600" 
        />
        <span className="text-xs font-black text-slate-800 w-10 text-right">{value}%</span>
      </div>
    </div>
  </div>
);

const MetricCard: React.FC<{ label: string; value: string; icon: string; highlight?: boolean; isActive?: boolean; isVerified?: boolean; onClick?: () => void }> = ({ label, value, icon, highlight, isActive, isVerified, onClick }) => (
  <button onClick={onClick} className={`p-5 rounded-2xl border flex items-center space-x-3 transition-all text-left w-full relative overflow-hidden active:scale-[0.98] ${isActive ? 'ring-2 ring-blue-600 bg-blue-600 border-blue-600 text-white shadow-xl' : highlight ? 'bg-slate-900 border-slate-800 text-white' : 'bg-white border-slate-100 shadow-sm text-gray-800 hover:border-blue-200 hover:bg-blue-50/20'}`}>
    {isVerified && !isActive && <div className="absolute top-0 right-0 bg-red-600 text-white text-[7px] font-black px-2 py-0.5 rounded-bl-lg uppercase tracking-tighter">Verified</div>}
    <div className={`w-10 h-10 rounded-xl flex items-center justify-center ${isActive ? 'bg-white/20' : highlight ? 'bg-white/10 text-blue-400' : 'bg-blue-50 text-blue-600'}`}>
      <i className={`fa-solid ${icon}`}></i>
    </div>
    <div className="flex-1 overflow-hidden">
      <p className={`text-[10px] uppercase font-black tracking-widest ${isActive ? 'text-white/70' : highlight ? 'text-slate-500' : 'text-gray-400'}`}>{label}</p>
      <p className="text-xl font-bold truncate">{value}</p>
    </div>
  </button>
);

export default ResultView;
